version: '2.4'

services:
  elasticsearch:
    image: {{image}}
    container_name: {{container_name}}
    ports:
      - 9200:9200
{{mapped-volumes}}
    user: ${CURRENT_UID}
{{/mapped-volumes}}
    environment:
      - cluster.name={{projectname}}-elasticsearch-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
    volumes:
{{mapped-volumes}}
      - ../.volumes/elasticsearch-data:/usr/share/elasticsearch/data:delegated
{{/mapped-volumes}}
{{named-volumes}}
      - elasticsearch-data:/usr/share/elasticsearch/data:delegated

volumes:
  elasticsearch-data:
    name: {{volumesPrefix}}-elasticsearch-data
{{/named-volumes}}
