services:
  mongo:
    image: {{image}}
    container_name: {{container_name}}
    ports:
      - 27017:27017
{{mapped-volumes}}
    user: '{{current_uid}}'
{{/mapped-volumes}}
    volumes:
{{mapped-volumes}}
      - ../.volumes/mongo-data:/data/db:delegated
{{/mapped-volumes}}
{{named-volumes}}
      - mongo-data:/data/db:delegated

volumes:
  mongo-data:
    name: {{volumesPrefix}}-mongo-data
    external: true
{{/named-volumes}}
