version: '2.4'

services:
  rabbitmq:
    image: {{image}}
    container_name: {{container_name}}
    hostname: {{container_name}}-host
    ports:
      - 5672:5672
      - 15672:15672
{{mapped-volumes}}
    user: '{{current_uid}}'
{{/mapped-volumes}}
    volumes:
{{mapped-volumes}}
      - ../.volumes/rabbit-data:/var/lib/rabbitmq/mnesia/rabbit@{{container_name}}-host
{{/mapped-volumes}}
{{named-volumes}}
      - rabbit-data:/var/lib/rabbitmq/mnesia/rabbit@{{container_name}}-host

volumes:
  rabbit-data:
    name: {{volumesPrefix}}-rabbit-data
    external: true
{{/named-volumes}}
